---
title: "validation of late phase biomarkers"
author: "Amrit Singh"
date: "Jan 6, 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse);
library(nlme)
library(ggrepel)
library(cowplot)
library(limma)
library(mixOmics)
library(grid)
library(cowplot)
library(ComplexHeatmap)
library(here)

source(here::here("src", "utils.R"))
```

## import data

```{r}
latephase_exacer_biomarkers <- readRDS(here::here("results", "latephase_exacer_biomarkers.rds"))
load(here::here("data", "preprocessedData", "geodatasets.RDATA"))

## samples in each dataset
table(phenoDataList$GSE19301$phenotype)

all(colnames(esetList$GSE19301) == rownames(phenoDataList$GSE19301))
geoPanelGenes <- as.data.frame(t(esetList$GSE19301))
geoPanelGenes <- geoPanelGenes[, intersect(colnames(geoPanelGenes), latephase_exacer_biomarkers)]

geoPanelGenes <-add_column(geoPanelGenes, donor = phenoDataList$GSE19301$donor, .before = 1)
geoPanelGenes <-add_column(geoPanelGenes, sex = phenoDataList$GSE19301$sex, .before = 1)
geoPanelGenes <-add_column(geoPanelGenes, phenotype = phenoDataList$GSE19301$phenotype, .before = 1)
```
## Exacerbation dataset

## compare quiet vs. exacer and followup vs. exacer

```{r}
mod_exacer <- run_lme(data = geoPanelGenes[phenoDataList$GSE19301$severity == "Moderate Persistent",], 
                  fdr = 0.1)
mod_exacer$severity <- "Moderate Persistent"
sev_exacer <- run_lme(data = geoPanelGenes[phenoDataList$GSE19301$severity == "Severe Persistent",], 
                  fdr = 0.1)
sev_exacer$severity <- "Severe Persistent"

exacer <- rbind(mod_exacer, sev_exacer)
```

## volcano plot

```{r}
scaleFUN <- function(x) sprintf("%.0f", x)
## Quiet vs. Excerbation
exacer$logPval <- -log10(exacer$`p-value`)
exacer$Sig <- ifelse(exacer$adj.P.Val < 0.1, "FDR<10%", "NotSignificant")
gg1 <- ggplot(exacer, aes(x = Value, y = logPval, color = Sig)) + geom_point(size = 2) +
  geom_vline(aes(xintercept = 0), lty = 2, color = "gray") +
  geom_text_repel(data=filter(exacer, adj.P.Val < 0.1), 
                  aes(label=feature), size=2, max.overlaps = 100) + 
  customTheme(sizeStripFont = 8, xAngle = 0, hjust = 0.5, vjust = 0.5, xSize = 8, ySize = 8, xAxisSize = 8, yAxisSize = 8) +
  scale_x_continuous(expression("log"[2]~"fold-change")) +
  scale_y_continuous(expression("-log"[10]~"P-value"), labels=scaleFUN) +
  scale_color_manual(values=c("blue", "gray")) +
  ggtitle("PBMCs - GSE19301") + 
  theme(legend.position = "bottom") +
  facet_grid(contrast ~ severity, scales = "free")

gg1 
```


```{r}
exacer %>% 
  group_by(severity, contrast, fc) %>% 
  filter(adj.P.Val < 0.1) %>% 
  summarise(n = n())


exacer %>% 
  group_by(severity, contrast, fc) %>% 
  filter(adj.P.Val < 0.1) %>% 
  filter(severity == "Severe Persistent", contrast == "Exacer - Quiet", fc == "DOWN") %>% 
  pull(feature)

```


## airway, blood, sputum and balf datasets

```{r}
select_gse <- c("GSE69683","GSE74986", "GSE147878+GSE161245", "GSE76262+GSE147880")
result <- mapply(function(x, y, z, tis){
  result = test_biomarkers(eset = x,
                  pheno = y,
                  biomarkers = latephase_exacer_biomarkers)
  result$GSE <- z
  result$tissue <- tis
  result
}, x = esetList[select_gse], 
y = phenoDataList[select_gse], 
z = select_gse,
tis = sapply(phenoDataList[select_gse], function(i){unique(i$sampletype)}),
SIMPLIFY = FALSE) %>% 
  do.call(rbind, .) %>% 
  mutate(fc = ifelse(logFC>0, "UP", "DOWN"))

## number of patients
table(phenoDataList$GSE19301$severity, phenoDataList$GSE19301$phenotype)
length(unique(phenoDataList$GSE19301$donor[phenoDataList$GSE19301$severity == "Mild Persistent"]))
length(unique(phenoDataList$GSE19301$donor[phenoDataList$GSE19301$severity == "Moderate Persistent"]))
length(unique(phenoDataList$GSE19301$donor[phenoDataList$GSE19301$severity == "Severe Persistent"]))
rowSums(sapply(phenoDataList[select_gse], function(i){table(i$phenotype)}))
```

## number of individuals in each datasets

## exacerbation datasets (GSE19301)

```{r}
phenoDataList$GSE19301 %>% 
  filter(severity != "Mild Persistent") %>% 
  group_by(donor) %>% 
  dplyr::slice(1) %>% 
  group_by(sex, severity) %>% 
  summarise(n = n()) %>% 
  spread(sex, n) %>% 
  mutate(total = `M`+`F`) %>% 
  mutate(percent_f = 100*signif(`F`/total, 2)) %>% 
  mutate(total_percentf = paste0(total, " (", percent_f, "%)"))
```


## severity datasets

```{r}

a=data.frame(sampletype = sapply(phenoDataList[select_gse], function(i){
  unique(i$sampletype)
})) %>% 
  mutate(gse = rownames(.))

b=lapply(select_gse, function(i){
  df <- as.data.frame(table(phenoDataList[[i]]$sex, phenoDataList[[i]]$phenotype))
  df$gse <- i
  df
}) %>% 
  do.call(rbind, .) %>% 
  spread(Var1, Freq) %>% 
  mutate(total = `F`+`M`) %>% 
  mutate(percent_f = 100*signif(`F`/total, 2))

inner_join(a, b, by="gse") %>% 
  mutate(gse_sample = paste0(sampletype, " (", gse, ")")) %>% 
  mutate(total_percentf = paste0(total, " (", percent_f, "%)")) %>% 
  dplyr::select(Var2, gse_sample, total_percentf) %>% 
  spread(gse_sample, total_percentf)

```


## volcano plot

```{r}
df <- result %>% 
  mutate(sig = -log10(P.Value)) %>% 
  mutate(Significance = ifelse(adj.P.Val < 0.1, "FDR<10%", "NotSignificant")) %>% 
  mutate(tissue_gse = paste(tissue, GSE, sep="_"))
p <- df %>% 
  ggplot(aes(x = logFC, y = sig, col = Significance)) +
  geom_point() +
# facet_grid(contrast~tissue_gse) +
  ggh4x::facet_grid2(vars(tissue_gse), vars(contrast),
                      scales = "free", independent = "all") + 
  scale_color_manual(values=c("blue", "gray")) +
  ggrepel::geom_text_repel(data= subset(df, adj.P.Val < 0.1), aes(label=feature), size=2, max.overlaps = 20) +
  geom_vline(xintercept = 0, linetype="dashed") + 
  theme(legend.position = "top") +
  customTheme(sizeStripFont = 8, xAngle = 0, hjust = 0.5, vjust = 0.5, xSize = 8, ySize = 8, xAxisSize = 8, yAxisSize = 8) +
  xlab(expression("log"[2]~"fold-change")) +
  ylab(expression("-log"[10]~"P-value"))
ggsave(here::here("results", "validation_of_late_phase_biomarkers_volcanoplots.png"),
       p, height = 11, width = 8)

p
```


```{r}
result %>% 
  group_by(tissue, contrast, fc) %>% 
  filter(adj.P.Val < 0.1) %>% 
  summarise(n = n()) %>% 
  spread(fc, n)


exacer %>% 
  group_by(severity, contrast, fc) %>% 
  filter(adj.P.Val < 0.1) %>% 
  filter(severity == "Severe Persistent", contrast == "Exacer - Quiet", fc == "DOWN") %>% 
  pull(feature)



```



## overlap between the signficant genes

```{r}
sig_result <- subset(result, adj.P.Val < 0.1)
sig_exacer <- subset(exacer, adj.P.Val < 0.1)
df_exacer <- data.frame(panel = paste0(sig_exacer$contrast, " (", sig_exacer$severity, sig_exacer$tissue, "-", sig_exacer$GSE, ")"),
           feature = sig_exacer$feature)
df_sev <- data.frame(panel = paste0(sig_result$contrast, " (", sig_result$tissue, "-", sig_result$GSE, ")"),
           feature = sig_result$feature)

library(UpSetR)
sigfeat1 <- split(df_exacer$feature, df_exacer$panel)
upset(fromList(sigfeat1), nsets = length(sigfeat1))
sigfeat2 <- split(df_sev$feature, df_sev$panel)
upset(fromList(sigfeat2), nsets = length(sigfeat2))
upset(fromList(c(sigfeat1, sigfeat2)), nsets = length(sigfeat1)+length(sigfeat2))
```

# plsda analysis 

## exacerbation data

```{r}
latephase_biomarkers <- readRDS(here::here("results", "latephase_biomarkers.rds"))
latephase_biomarkers$all <- latephase_exacer_biomarkers
# exacer_plsda <- lapply(names(latephase_biomarkers), function(i){
#   biomarkers <- latephase_biomarkers[[i]]
#   ## all subjects
#   demo <- subset(phenoDataList$GSE19301, severity == "Moderate Persistent")
#   eset <- esetList$GSE19301[intersect(rownames(esetList$GSE19301), biomarkers), rownames(demo)]
#   exacer_all_mod <- multilevel_plsda(eset = eset, demo = demo, 
#                    biomarkers = biomarkers)
#   exacer_all_mod$df$comparison <- exacer_all_mod$feat$comparison <- paste(exacer_all_mod$df$comp, "(Moderate Persistent)")
#   exacer_all_mod$df$sex <- exacer_all_mod$feat$sex <- "M+F"
#   demo <- subset(phenoDataList$GSE19301, severity == "Severe Persistent")
#   eset <- esetList$GSE19301[intersect(rownames(esetList$GSE19301), biomarkers), rownames(demo)]
#   exacer_all_sev <- multilevel_plsda(eset = eset, demo = demo, 
#                    biomarkers = biomarkers)
#   exacer_all_sev$df$comparison <- exacer_all_sev$feat$comparison <- paste(exacer_all_sev$df$comp, "(Severe Persistent)")
#   exacer_all_sev$df$sex <- exacer_all_sev$feat$sex <- "M+F"
#   
#   ## females
#   demo <- subset(phenoDataList$GSE19301, severity == "Moderate Persistent" & sex ==  "F")
#   eset <- esetList$GSE19301[intersect(rownames(esetList$GSE19301), biomarkers), rownames(demo)]
#   exacer_f_mod <- multilevel_plsda(eset = eset, demo = demo, 
#                    biomarkers = biomarkers)
#   exacer_f_mod$df$comparison <- exacer_f_mod$feat$comparison <- paste(exacer_f_mod$df$comp, "(Moderate Persistent)")
#   exacer_f_mod$df$sex <- exacer_f_mod$feat$sex <- "F"
#   demo <- subset(phenoDataList$GSE19301, severity == "Severe Persistent" & sex ==  "F")
#   eset <- esetList$GSE19301[intersect(rownames(esetList$GSE19301), biomarkers), rownames(demo)]
#   exacer_f_sev <- multilevel_plsda(eset = eset, demo = demo, 
#                    biomarkers = biomarkers)
#   exacer_f_sev$df$comparison <- exacer_f_sev$feat$comparison <- paste(exacer_f_sev$df$comp, "(Severe Persistent)")
#   exacer_f_sev$df$sex <- exacer_f_sev$feat$sex <- "F"
#   
#   ## males
#   demo <- subset(phenoDataList$GSE19301, severity == "Moderate Persistent" & sex ==  "M")
#   eset <- esetList$GSE19301[intersect(rownames(esetList$GSE19301), biomarkers), rownames(demo)]
#   exacer_m_mod <- multilevel_plsda(eset = eset, demo = demo, 
#                    biomarkers = biomarkers)
#   exacer_m_mod$df$comparison <- exacer_m_mod$feat$comparison <- paste(exacer_m_mod$df$comp, "(Moderate Persistent)")
#   exacer_m_mod$df$sex <- exacer_m_mod$feat$sex <- "M"
#   demo <- subset(phenoDataList$GSE19301, severity == "Severe Persistent" & sex ==  "M")
#   eset <- esetList$GSE19301[intersect(rownames(esetList$GSE19301), biomarkers), rownames(demo)]
#   exacer_m_sev <- multilevel_plsda(eset = eset, demo = demo, 
#                    biomarkers = biomarkers)
#   exacer_m_sev$df$comparison <- exacer_m_sev$feat$comparison <- paste(exacer_m_sev$df$comp, "(Severe Persistent)")
#   exacer_m_sev$df$sex <- exacer_m_sev$feat$sex <- "M"
#   
#   exacer_df <- rbind(exacer_all_mod$df, exacer_all_sev$df,
#                   exacer_f_mod$df, exacer_f_sev$df,
#                   exacer_m_mod$df, exacer_m_sev$df)
#   exacer_feat <- rbind(exacer_all_mod$feat, exacer_all_sev$feat,
#                 exacer_f_mod$feat, exacer_f_sev$feat,
#                 exacer_m_mod$feat, exacer_m_sev$feat)
#   exacer_df$panel <- exacer_feat$panel <- i
#   list(df = exacer_df, feat = exacer_feat)
# }) %>% 
#   zip_nPure()
# saveRDS(exacer_plsda, here("results", "exacer_plsda.rds"))
```

```{r}
exacer_plsda <- readRDS(here("results", "exacer_plsda.rds"))
col_names <- c("value", "stat", "gse", "sampletype", "comparison", "panel", "sex")
panel_names <- c("all", "panCancer", "UCSC_isoforms", "UCSC", "Ensembl", "Trinity")
auc <- do.call(rbind, exacer_plsda$df)[, col_names] %>% 
  filter(stat == "AUC.mean") %>% 
  dplyr::select(-stat) %>% 
  spread(panel, value)

auc0 <- auc[, panel_names]
row_ha <- rowAnnotation(sampletype=auc$sampletype,
                        comparison=auc$comparison, sex=auc$sex,
                        col = list(sampletype = c("blood" = "red"),
                                   comparison = c("Exacer vs. Quiet (Moderate Persistent)"="#DEEBF7", "Exacer vs. Quiet (Severe Persistent)"="#9ECAE1", "Exacer vs. followup (Moderate Persistent)"="#4292C6", "Exacer vs. followup (Severe Persistent)"="#084594"),
                                   sex = c("F"="#80CDC1","M"="#35978F","M+F"="#01665E")))

pdf(here::here("results", "lar_mrna_biomarkers_exacerbations.pdf"),
    height = 4, width = 6)
Heatmap(auc0, right_annotation = row_ha, 
        cluster_columns = FALSE,
        border = TRUE, name="AUC",
    cell_fun = function(j, i, x, y, width, height, fill) {
        if(auc0[i, j] > 0.9) {
          grid.text("***", x, y, gp = gpar(fontsize = 15))
        } else if(auc0[i, j] > 0.8) {
          grid.text("**", x, y, gp = gpar(fontsize = 15))
        } else if(auc0[i, j] > 0.7) {
          grid.text("*", x, y, gp = gpar(fontsize = 15))
        }
})
dev.off()

## save data
exacertable <- do.call(rbind, exacer_plsda$df)[, col_names] %>% 
  mutate(value = signif(value, 2)) %>%  
  spread(stat, value) %>% 
  arrange(desc(AUC.mean))
write.csv(exacertable, here::here("results", "exacerbation_models_perfs.csv"))

```

## summarise models

```{r}
auc0.9 <- subset(exacertable, AUC.mean > 0.9)
auc0.8 <- subset(exacertable, AUC.mean > 0.8)
auc0.7 <- subset(exacertable, AUC.mean > 0.7)
print(paste0("number of panels with AUC>0.9: ", nrow(auc0.9)))
print(paste0("number of panels with AUC>0.8: ", nrow(auc0.8)))
print(paste0("number of panels with AUC>0.7: ", nrow(auc0.7)))
print(table(auc0.7$sex))
print(table(auc0.7$comparison))
print(table(auc0.7$panel))

auc0.7_quiet <- auc0.7[grep("Quiet", auc0.7$comparison), ]
table(auc0.7_quiet$sex)
auc0.7_followup <- auc0.7[grep("followup", auc0.7$comparison), ]
table(auc0.7_followup$sex)
print(paste0("number of (exacer vs. quiet) panels with AUC>0.7: ", nrow(auc0.7_quiet)))
print(paste0("number of (exacer vs. followup panels with AUC>0.7: ", nrow(auc0.7_followup)))

```


```{r}

keep_panels <- do.call(rbind, exacer_plsda$df)[, col_names] %>% 
  filter(stat == "AUC.mean") %>% 
  dplyr::select(-stat) %>% 
  filter(value > 0.80)

exacer_top_feat <- do.call(rbind, exacer_plsda$feat) %>% 
  filter(paste0(gse,comparison,sex,panel) %in% paste0(keep_panels$gse,keep_panels$comparison,keep_panels$sex,keep_panels$panel)) %>% 
  group_by(panel, comparison, comp, gse) %>% 
  arrange(desc(abs(value.var))) %>% 
  dplyr::slice(1:10) %>% 
  group_by(feature, comparison) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  dplyr::slice(1:25)

exacer_top_feat_levels <- exacer_top_feat %>% 
  group_by(feature) %>% 
  summarise(total = sum(n)) %>% 
  arrange(desc(total)) %>% 
  dplyr::slice(1:20)

p <- exacer_top_feat %>% 
  filter(feature %in% exacer_top_feat_levels$feature) %>% 
  mutate(feature = factor(feature, rev(exacer_top_feat_levels$feature))) %>% 
  ggplot(aes(y = feature, x = n, fill = comparison)) +
  geom_bar(stat = "identity", color = "black") +
  theme_bw() +
  ylab("mRNA biomarker") +
  xlab("Frequency") +
  theme(legend.position = c(0.8, 0.2))+
  theme(axis.text.y = element_text(face = "italic"))
ggsave(here::here("results", "top_features_asthma_exacerbations.png"), p,
       height = 4, width = 8)
```

```{r}
lar_de_toptable <- readRDS(here::here("results", "lar_de_toptable.rds")) %>% 
  mutate(fc = ifelse(logFC >0, "UP", "DOWN"),
         tissue = "blood",
         contrast = "ER vs. DR") %>% 
  dplyr::rename(feature=Gene)
selectcols <- c("fc", "contrast", "feature", "tissue")
a=exacer %>% 
  mutate(contrast = paste(contrast, severity, sep="-")) %>% 
  dplyr::rename(logFC=Value)
nes0 <- rbind(subset(a, feature %in% exacer_top_feat$feature)[, selectcols],
      subset(result, feature %in% exacer_top_feat$feature)[, selectcols],
      subset(lar_de_toptable, feature %in% exacer_top_feat$feature)[, selectcols])

b = nes0 %>% spread(feature, fc)
nes <- b[, -c(1, 2)]
rownames(nes) <- NULL
row_ha <- rowAnnotation(contrast=b$contrast,
                        tissue=b$tissue)

Heatmap(nes, right_annotation = row_ha, 
        col = c("UP"="red", "DOWN"="lightblue"),
        cluster_columns = FALSE,
        border = TRUE, name="FC")
```

## severity data

```{r}
# lar_plsda = function(eset_list, pheno_list, gse_list, biomarkers){
#   res <- mapply(function(x, y, gse){
#     x = x[, rownames(y)]
#     group <- y$phenotype
#     ## healthyControls vs. moderateAsthma
#     X <- t(x[intersect(rownames(x), biomarkers), group != "severeAsthma"])
#     Y <- droplevels(group[group != "severeAsthma"])
#     result <- mixOmics::plsda(X = X, Y = Y, ncomp=2)
#     cv <- perf(result, validation = "Mfold", folds = 5, nrepeat = 20, auc = TRUE)
#     df1 <- data.frame(value = cv$auc$comp2, 
#                stat = names(cv$auc$comp2),
#                gse = gse,
#                sampletype = unique(y$sampletype),
#                comparison = "healthyControls_vs_moderateAsthma")
#    feat1_comp1 <- selectVar(result, comp=1)$value %>% 
#      mutate(feature = rownames(.)) %>% 
#      mutate(gse = gse, 
#             comp = 1,
#             comparison = "healthyControls_vs_moderateAsthma")
#    feat1_comp2 <- selectVar(result, comp=2)$value %>% 
#      mutate(feature = rownames(.)) %>% 
#      mutate(gse = gse, 
#             comp = 2,
#             comparison = "healthyControls_vs_moderateAsthma")
#    feat1 <- rbind(feat1_comp1, feat1_comp2)
#     
#     ## healthyControls vs. severeAsthma
#     X <- t(x[intersect(rownames(x), biomarkers), group != "moderateAsthma"])
#     Y <- droplevels(group[group != "moderateAsthma"])
#     result <- mixOmics::plsda(X = X, Y = Y, ncomp=2)
#     cv <- perf(result, validation = "Mfold", folds = 5, nrepeat = 20, auc = TRUE)
#     df2 <- data.frame(value = cv$auc$comp2, 
#                stat = names(cv$auc$comp2),
#                gse = gse,
#                sampletype = unique(y$sampletype),
#                comparison = "healthyControls_vs_severeAsthma")
#    feat2_comp1 <- selectVar(result, comp=1)$value %>% 
#      mutate(feature = rownames(.)) %>% 
#      mutate(gse = gse, 
#             comp = 1,
#             comparison = "healthyControls_vs_severeAsthma")
#    feat2_comp2 <- selectVar(result, comp=2)$value %>% 
#      mutate(feature = rownames(.)) %>% 
#      mutate(gse = gse, 
#             comp = 2,
#             comparison = "healthyControls_vs_severeAsthma")
#    feat2 <- rbind(feat2_comp1, feat2_comp2)
#     
#     ## moderateAsthma vs. severeAsthma
#     X <- t(x[intersect(rownames(x), biomarkers), group != "healthyControls"])
#     Y <- droplevels(group[group != "healthyControls"])
#     result <- mixOmics::plsda(X = X, Y = Y, ncomp=2)
#     cv <- perf(result, validation = "Mfold", folds = 5, nrepeat = 20, auc = TRUE)
#     df3 <- data.frame(value = cv$auc$comp2, 
#                stat = names(cv$auc$comp2),
#                gse = gse,
#                sampletype = unique(y$sampletype),
#                comparison = "moderateAsthma_vs_severeAsthma")
#    feat3_comp1 <- selectVar(result, comp=1)$value %>% 
#      mutate(feature = rownames(.)) %>% 
#      mutate(gse = gse, 
#             comp = 1,
#             comparison = "moderateAsthma_vs_severeAsthma")
#    feat3_comp2 <- selectVar(result, comp=2)$value %>% 
#      mutate(feature = rownames(.)) %>% 
#      mutate(gse = gse, 
#             comp = 2,
#             comparison = "moderateAsthma_vs_severeAsthma")
#    feat3 <- rbind(feat3_comp1, feat3_comp2)
#     
#     ## feature ranking
#     feat <- rbind(feat1, feat2, feat3)
#     
#     ## perf results
#     df <- rbind(df1, df2, df3)
#     list(feat=feat, df=df)
# }, x = eset_list[gse_list], y = pheno_list[gse_list], gse = gse_list,
# SIMPLIFY = FALSE) %>% 
#   zip_nPure()
#   return(res)
# }
# 
# all_sev <- lapply(names(latephase_biomarkers), function(i){
#   res <- lar_plsda(eset_list = esetList, pheno_list = phenoDataList, gse_list = select_gse, 
#                      biomarkers = latephase_biomarkers[[i]])
#   list(feat = do.call(rbind, res$feat) %>% mutate(panel = i),
#        df = do.call(rbind, res$df) %>% mutate(panel = i))
# }) %>% 
#   zip_nPure()
# pheno = lapply(phenoDataList, function(i){subset(i, sex == "F")})
# f_sev <- lapply(names(latephase_biomarkers), function(i){
#   res <- lar_plsda(eset_list = esetList, pheno_list = pheno, gse_list = select_gse, 
#                      biomarkers = latephase_biomarkers[[i]])
#   list(feat = do.call(rbind, res$feat) %>% mutate(panel = i),
#        df = do.call(rbind, res$df) %>% mutate(panel = i))
# }) %>% 
#   zip_nPure()
# pheno = lapply(phenoDataList, function(i){subset(i, sex == "M")})
# m_sev <- lapply(names(latephase_biomarkers), function(i){
#   res <- lar_plsda(eset_list = esetList, pheno_list = pheno, gse_list = select_gse, 
#                      biomarkers = latephase_biomarkers[[i]])
#   list(feat = do.call(rbind, res$feat) %>% mutate(panel = i),
#        df = do.call(rbind, res$df) %>% mutate(panel = i))
# }) %>% 
#   zip_nPure()
# 
# saveRDS(all_sev, here("results", "all_sev.rds"))
# saveRDS(f_sev, here("results", "f_sev.rds"))
# saveRDS(m_sev, here("results", "m_sev.rds"))
all_sev <- readRDS(here("results", "all_sev.rds"))
f_sev <- readRDS(here("results", "f_sev.rds"))
m_sev <- readRDS(here("results", "m_sev.rds"))

sev <- rbind(do.call(rbind, all_sev$df) %>% mutate(sex="M+F"),
      do.call(rbind, f_sev$df) %>% mutate(sex="F"),
      do.call(rbind, m_sev$df) %>% mutate(sex="M"))
sev$sampletype[sev$sampletype == "balf"] <- "BALF"
```

## summarise models

```{r}
sevtable <- sev %>% 
  spread(stat, value) %>% 
  mutate(AUC.mean = signif(AUC.mean, 2),
         AUC.sd = signif(AUC.sd, 2))
sev_hc <- sevtable[grep("healthyControls", sevtable$comparison), ] %>%  
  arrange(desc(AUC.mean))
sev_hc0.9 <- subset(sev_hc, AUC.mean > 0.9)
sev_hc0.8 <- subset(sev_hc, AUC.mean > 0.8)
sev_hc0.7 <- subset(sev_hc, AUC.mean > 0.7)
sev_asthma <- sevtable[-grep("healthyControls", sevtable$comparison), ] %>%  
  arrange(desc(AUC.mean))
sev_asthma0.9 <- subset(sev_asthma, AUC.mean > 0.9)
sev_asthma0.8 <- subset(sev_asthma, AUC.mean > 0.8)
sev_asthma0.7 <- subset(sev_asthma, AUC.mean > 0.7)
write.csv(sev_hc, here::here("results", "severity_hc_models_perfs.csv"))
write.csv(sev_asthma, here::here("results", "severity_asthma_models_perfs.csv"))
  

print(paste0("total number of hc vs asthma panels: ", nrow(sev_hc)))
print(paste0("number of hc vs asthma panels with AUC>0.9: ", nrow(sev_hc0.9)))
print(paste0("number of hc vs asthma panels with AUC>0.8: ", nrow(sev_hc0.8)))
print(paste0("number of hc vs asthma panels with AUC>0.7: ", nrow(sev_hc0.7)))
print(table(sev_hc0.7$sex))
print(table(sev_hc0.7$comparison))
print(table(sev_hc0.7$panel))
print(table(sev_hc0.7$sampletype))

print(paste0("total number of mod vs. sev asthma panels: ", nrow(sev_asthma)))
print(paste0("number of mod vs. sev asthma panels with AUC>0.9: ", nrow(sev_asthma0.9)))
print(paste0("number of mod vs. sev asthma panels with AUC>0.8: ", nrow(sev_asthma0.8)))
print(paste0("number of mod vs. sev asthma panels with AUC>0.7: ", nrow(sev_asthma0.7)))
print(table(sev_asthma0.7$sex))
print(table(sev_asthma0.7$comparison))
print(table(sev_asthma0.7$panel))
print(table(sev_asthma0.7$sampletype))



auc0.7_quiet <- auc0.7[grep("Quiet", auc0.7$comparison), ]
table(auc0.7_quiet$sex)
auc0.7_followup <- auc0.7[grep("followup", auc0.7$comparison), ]
table(auc0.7_followup$sex)
print(paste0("number of (exacer vs. quiet) panels with AUC>0.7: ", nrow(auc0.7_quiet)))
print(paste0("number of (exacer vs. followup panels with AUC>0.7: ", nrow(auc0.7_followup)))

```


```{r}
auc <- sev[, col_names] %>% 
  filter(stat == "AUC.mean") %>% 
  dplyr::select(-stat) %>% 
  spread(panel, value)

auc0 <- auc[, panel_names]
row_ha <- rowAnnotation(sampletype=auc$sampletype,
                        comparison=auc$comparison, sex=auc$sex,
                        col = list(sampletype = c("airway"="#DEEBF7","BALF"="#9ECAE1","induced sputum"="#4292C6", "blood" = "red"),
                                   comparison = c("healthyControls_vs_moderateAsthma"="#E69F00", "healthyControls_vs_severeAsthma"="#56B4E9", "moderateAsthma_vs_severeAsthma"="#009E73"),
                                   sex = c("F"="#80CDC1","M"="#35978F","M+F"="#01665E")))
comptype <- auc$comparison
comptype[grep("healthyControls", comptype)] <- "HC"
comptype[-grep("HC", comptype)] <- "Asthma"
pdf(here::here("results", "lar_mrna_biomarkers_severity.pdf"),
    height = 8, width = 10)
Heatmap(auc0, right_annotation = row_ha, cluster_columns = FALSE,
        border = TRUE, name="AUC", row_split = comptype,
    cell_fun = function(j, i, x, y, width, height, fill) {
        if(auc0[i, j] > 0.9) {
          grid.text("***", x, y, gp = gpar(fontsize = 15))
        } else if(auc0[i, j] > 0.8) {
          grid.text("**", x, y, gp = gpar(fontsize = 15))
        } else if(auc0[i, j] > 0.7) {
          grid.text("*", x, y, gp = gpar(fontsize = 15))
        }
})
dev.off()

```


```{r}

keep_panels <- sev %>% 
  filter(stat == "AUC.mean") %>% 
  # filter(!grepl("healthyControls", comparison)) %>% 
  dplyr::select(-stat) %>% 
  filter(value > 0.70)

sev_feat <- rbind(do.call(rbind, all_sev$feat) %>% mutate(sex="M+F"),
      do.call(rbind, f_sev$feat) %>% mutate(sex="F"),
      do.call(rbind, m_sev$feat) %>% mutate(sex="M"))

sev_feat_top <- sev_feat %>% 
  filter(paste0(gse,comparison,sex,panel) %in% paste0(keep_panels$gse,keep_panels$comparison,keep_panels$sex,keep_panels$panel)) %>% 
  group_by(panel, comparison, comp, gse) %>% 
  arrange(desc(abs(value.var))) %>% 
  dplyr::slice(1:10) %>% 
  group_by(feature, comparison) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  dplyr::slice(1:25)

sev_feat_top_levels <- sev_feat_top %>% 
  group_by(feature) %>% 
  summarise(total = sum(n)) %>% 
  arrange(desc(total)) %>% 
  dplyr::slice(1:30)

p <- sev_feat_top %>% 
  filter(feature %in% sev_feat_top_levels$feature) %>% 
  mutate(feature = factor(feature, rev(sev_feat_top_levels$feature))) %>% 
  ggplot(aes(y = feature, x = n, fill = comparison)) +
  geom_bar(stat = "identity", color = "black") +
  theme_bw() +
  ylab("mRNA biomarker") +
  xlab("Frequency") +
  theme(legend.position = c(0.7, 0.1))+
  theme(axis.text.y = element_text(face = "italic"))
ggsave(here::here("results", "top_features_asthma_severity.png"), p,
       height = 8, width = 7)
```


```{r}
sev_feat_top <- sev_feat %>% 
filter(paste0(gse,comparison,sex,panel) %in% paste0(keep_panels$gse,keep_panels$comparison,keep_panels$sex,keep_panels$panel)) %>% 
  group_by(panel, comparison, comp, gse) %>% 
  arrange(desc(abs(value.var))) %>% 
  dplyr::slice(1:10) %>% 
  group_by(feature) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  dplyr::slice(1:25)

lar_de_toptable <- readRDS(here::here("results", "lar_de_toptable.rds")) %>% 
  mutate(fc = ifelse(logFC >0, "UP", "DOWN"),
         tissue = "blood",
         contrast = "ER vs. DR") %>% 
  dplyr::rename(feature=Gene)
selectcols <- c("fc", "contrast", "feature", "tissue")
a=exacer %>% 
  mutate(contrast = paste(contrast, severity, sep="-")) %>% 
  dplyr::rename(logFC=Value)
nes0 <- rbind(subset(a, feature %in% sev_feat_top$feature)[, selectcols],
      subset(result, feature %in% sev_feat_top$feature)[, selectcols],
      subset(lar_de_toptable, feature %in% sev_feat_top$feature)[, selectcols])

b = nes0 %>% spread(feature, fc)
nes <- b[, -c(1, 2)]
rownames(nes) <- NULL
row_ha <- rowAnnotation(contrast=b$contrast,
                        tissue=b$tissue)

Heatmap(nes, right_annotation = row_ha, 
        col = c("UP"="red", "DOWN"="lightblue"),
        cluster_columns = FALSE,
        border = TRUE, name="FC")
```

